### ISSUE TITLE
midori not start on openSuse

### ISSUE THREAD

**Issue by virdignus** [eustasy/midori-browser.org#92]
midori not started on openSuse
OS: openSUSE Tumbleweed (20160813) (x86_64)
error:
```
~> midori
Ошибка сегментирования (core dumped)
```
```
~> midori --debug
Launching command: '/usr/bin/gdb' --batch -ex 'set print thread-events off' -ex run -ex 'set logging on /run/user/1000/midori/gdb.bt' -ex 'bt' --return-child-result --args midori 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Thread 1 "midori" received signal SIGSEGV, Segmentation fault.
0x00007ffff23a2f48 in WTF::String::isolatedCopy() const () from /usr/lib64/libjavascriptcoregtk-1.0.so.0
#0  0x00007ffff23a2f48 in WTF::String::isolatedCopy() const () from /usr/lib64/libjavascriptcoregtk-1.0.so.0
#1  0x00007ffff1f1b524 in OpaqueJSString::string() const () from /usr/lib64/libjavascriptcoregtk-1.0.so.0
#2  0x00007ffff1ef64cb in JSEvaluateScript () from /usr/lib64/libjavascriptcoregtk-1.0.so.0
#3  0x00007ffff7b72dcf in sokoke_js_script_eval () from /usr/lib64/libmidori-core.so.1
#4  0x00007ffff7b93d45 in midori_speed_dial_construct () from /usr/lib64/libmidori-core.so.1
#5  0x00007ffff7b593f9 in midori_normal_app_new () from /usr/lib64/libmidori-core.so.1
#6  0x000000000040352c in main ()
 #```

**Comment by lewisgoddard** [comment]
Also, this really isn't the place for support calls for Midori, it's for the development of the Midori-Browser.org website. On that note, you should be better off asking on #midori on IRC.
